//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmitraEmitraEncrytDecryptClient
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EmitraEmitraEncrytDecryptClient.EmitraEncrytDecryptSoap")]
    public interface EmitraEncrytDecryptSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<EmitraEmitraEncrytDecryptClient.HelloWorldResponse> HelloWorldAsync(EmitraEmitraEncrytDecryptClient.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EmitraEncryptString", ReplyAction="*")]
        System.Threading.Tasks.Task<EmitraEmitraEncrytDecryptClient.EmitraEncryptStringResponse> EmitraEncryptStringAsync(EmitraEmitraEncrytDecryptClient.EmitraEncryptStringRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EmitraDecriptString", ReplyAction="*")]
        System.Threading.Tasks.Task<EmitraEmitraEncrytDecryptClient.EmitraDecriptStringResponse> EmitraDecriptStringAsync(EmitraEmitraEncrytDecryptClient.EmitraDecriptStringRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public EmitraEmitraEncrytDecryptClient.HelloWorldRequestBody Body;
        
        public HelloWorldRequest()
        {
        }
        
        public HelloWorldRequest(EmitraEmitraEncrytDecryptClient.HelloWorldRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody
    {
        
        public HelloWorldRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public EmitraEmitraEncrytDecryptClient.HelloWorldResponseBody Body;
        
        public HelloWorldResponse()
        {
        }
        
        public HelloWorldResponse(EmitraEmitraEncrytDecryptClient.HelloWorldResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody()
        {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult)
        {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EmitraEncryptStringRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EmitraEncryptString", Namespace="http://tempuri.org/", Order=0)]
        public EmitraEmitraEncrytDecryptClient.EmitraEncryptStringRequestBody Body;
        
        public EmitraEncryptStringRequest()
        {
        }
        
        public EmitraEncryptStringRequest(EmitraEmitraEncrytDecryptClient.EmitraEncryptStringRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EmitraEncryptStringRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string EncryptionKey;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string strData;
        
        public EmitraEncryptStringRequestBody()
        {
        }
        
        public EmitraEncryptStringRequestBody(string EncryptionKey, string strData)
        {
            this.EncryptionKey = EncryptionKey;
            this.strData = strData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EmitraEncryptStringResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EmitraEncryptStringResponse", Namespace="http://tempuri.org/", Order=0)]
        public EmitraEmitraEncrytDecryptClient.EmitraEncryptStringResponseBody Body;
        
        public EmitraEncryptStringResponse()
        {
        }
        
        public EmitraEncryptStringResponse(EmitraEmitraEncrytDecryptClient.EmitraEncryptStringResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EmitraEncryptStringResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string EmitraEncryptStringResult;
        
        public EmitraEncryptStringResponseBody()
        {
        }
        
        public EmitraEncryptStringResponseBody(string EmitraEncryptStringResult)
        {
            this.EmitraEncryptStringResult = EmitraEncryptStringResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EmitraDecriptStringRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EmitraDecriptString", Namespace="http://tempuri.org/", Order=0)]
        public EmitraEmitraEncrytDecryptClient.EmitraDecriptStringRequestBody Body;
        
        public EmitraDecriptStringRequest()
        {
        }
        
        public EmitraDecriptStringRequest(EmitraEmitraEncrytDecryptClient.EmitraDecriptStringRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EmitraDecriptStringRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string EncryptionKey;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string strData;
        
        public EmitraDecriptStringRequestBody()
        {
        }
        
        public EmitraDecriptStringRequestBody(string EncryptionKey, string strData)
        {
            this.EncryptionKey = EncryptionKey;
            this.strData = strData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EmitraDecriptStringResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EmitraDecriptStringResponse", Namespace="http://tempuri.org/", Order=0)]
        public EmitraEmitraEncrytDecryptClient.EmitraDecriptStringResponseBody Body;
        
        public EmitraDecriptStringResponse()
        {
        }
        
        public EmitraDecriptStringResponse(EmitraEmitraEncrytDecryptClient.EmitraDecriptStringResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EmitraDecriptStringResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string EmitraDecriptStringResult;
        
        public EmitraDecriptStringResponseBody()
        {
        }
        
        public EmitraDecriptStringResponseBody(string EmitraDecriptStringResult)
        {
            this.EmitraDecriptStringResult = EmitraDecriptStringResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface EmitraEncrytDecryptSoapChannel : EmitraEmitraEncrytDecryptClient.EmitraEncrytDecryptSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class EmitraEncrytDecryptSoapClient : System.ServiceModel.ClientBase<EmitraEmitraEncrytDecryptClient.EmitraEncrytDecryptSoap>, EmitraEmitraEncrytDecryptClient.EmitraEncrytDecryptSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public EmitraEncrytDecryptSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(EmitraEncrytDecryptSoapClient.GetBindingForEndpoint(endpointConfiguration), EmitraEncrytDecryptSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public EmitraEncrytDecryptSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(EmitraEncrytDecryptSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public EmitraEncrytDecryptSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(EmitraEncrytDecryptSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public EmitraEncrytDecryptSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EmitraEmitraEncrytDecryptClient.HelloWorldResponse> EmitraEmitraEncrytDecryptClient.EmitraEncrytDecryptSoap.HelloWorldAsync(EmitraEmitraEncrytDecryptClient.HelloWorldRequest request)
        {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<EmitraEmitraEncrytDecryptClient.HelloWorldResponse> HelloWorldAsync()
        {
            EmitraEmitraEncrytDecryptClient.HelloWorldRequest inValue = new EmitraEmitraEncrytDecryptClient.HelloWorldRequest();
            inValue.Body = new EmitraEmitraEncrytDecryptClient.HelloWorldRequestBody();
            return ((EmitraEmitraEncrytDecryptClient.EmitraEncrytDecryptSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EmitraEmitraEncrytDecryptClient.EmitraEncryptStringResponse> EmitraEmitraEncrytDecryptClient.EmitraEncrytDecryptSoap.EmitraEncryptStringAsync(EmitraEmitraEncrytDecryptClient.EmitraEncryptStringRequest request)
        {
            return base.Channel.EmitraEncryptStringAsync(request);
        }
        
        public System.Threading.Tasks.Task<EmitraEmitraEncrytDecryptClient.EmitraEncryptStringResponse> EmitraEncryptStringAsync(string EncryptionKey, string strData)
        {
            EmitraEmitraEncrytDecryptClient.EmitraEncryptStringRequest inValue = new EmitraEmitraEncrytDecryptClient.EmitraEncryptStringRequest();
            inValue.Body = new EmitraEmitraEncrytDecryptClient.EmitraEncryptStringRequestBody();
            inValue.Body.EncryptionKey = EncryptionKey;
            inValue.Body.strData = strData;
            return ((EmitraEmitraEncrytDecryptClient.EmitraEncrytDecryptSoap)(this)).EmitraEncryptStringAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EmitraEmitraEncrytDecryptClient.EmitraDecriptStringResponse> EmitraEmitraEncrytDecryptClient.EmitraEncrytDecryptSoap.EmitraDecriptStringAsync(EmitraEmitraEncrytDecryptClient.EmitraDecriptStringRequest request)
        {
            return base.Channel.EmitraDecriptStringAsync(request);
        }
        
        public System.Threading.Tasks.Task<EmitraEmitraEncrytDecryptClient.EmitraDecriptStringResponse> EmitraDecriptStringAsync(string EncryptionKey, string strData)
        {
            EmitraEmitraEncrytDecryptClient.EmitraDecriptStringRequest inValue = new EmitraEmitraEncrytDecryptClient.EmitraDecriptStringRequest();
            inValue.Body = new EmitraEmitraEncrytDecryptClient.EmitraDecriptStringRequestBody();
            inValue.Body.EncryptionKey = EncryptionKey;
            inValue.Body.strData = strData;
            return ((EmitraEmitraEncrytDecryptClient.EmitraEncrytDecryptSoap)(this)).EmitraDecriptStringAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.EmitraEncrytDecryptSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.EmitraEncrytDecryptSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.EmitraEncrytDecryptSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://localhost:44319/EmitraEncrytDecrypt.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.EmitraEncrytDecryptSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://localhost:44319/EmitraEncrytDecrypt.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            EmitraEncrytDecryptSoap,
            
            EmitraEncrytDecryptSoap12,
        }
    }
}
